### ISSUE TITLE
showing me sub collection name as column 4

### ISSUE THREAD

**Issue by dipeshkakkad** [ergophobe/shopify-breadcrumbs#1]
Hello
I need your help I am using your breadcrumb in my theme when I go to my collection name as 'glass' then go to collection name as 'Rayban' and select product then it will show me in breadcrumb name as column 4 instead of showing RayBan collection name.

please see this screenshot https://prnt.sc/tae9dw

Thank you kind regards.

**Comment by dipeshkakkad** [comment]
No need any help I just found column 4 name in navigation menu.
Thank you for your time.

**Comment by ergophobe** [comment]
That'll do it!
